# Generated by Django 5.0.6 on 2024-05-31 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_rename_menu_menuitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='bookingDate',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='no_of_guests',
            new_name='guests',
        ),
    ]
